image: python:3.7

test:
  script:
  # Install Python packages required to run code. Add any additional
  # packages your code needs require here.
  - pip install dateutils flake8 matplotlib numpy pytest requests

  # flake8 static code and style testing. Enable for extra testing.
  # - python -m flake8 .

    # Run unit tests
  - python -m pytest -v .

  # Run deliverables. Add your deliverables to the test system here.
  - python Task1A.py

  - python Task2A.py
  - python Task2D.py
